server:
  port: 8602 # 服务消费方

# 指定当前eureka客户端的注册地址,
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8501/eureka
  instance:
    hostname: 127.0.0.1

#当前服务名称
spring:
  application:
    name: eureka-consumer